# only applied when using embedded server
server:
  port: 8081
  session:
    timeout: 86400
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png