# only applied when using embedded server
server:
  port: 8081
  session:
    timeout: 86400
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png